<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Articles</title>
</head>
<body>
    <h1><?php echo $article->getName(); ?></h1>
    <ul>
        <?php foreach ($categories as $category) : ?>
            <li>
                <a href="/category/<?php echo $category->getId(); ?>"><?php echo $category->getName(); ?></a>
            </li>
        <?php endforeach ?>

    </ul>
</body>
</html>